// Automatically generated by astro-icon
// 18b9b63c8fed80aaa1d4d849596360e1348f98a3d9a27e01c4a21a4021a2e28a

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "astro"
		| "circumpunct"
		| "compare"
		| "copy"
		| "info"
		| "left-to-line"
		| "right-arrow"
		| "share"
		| "tailwind"
		| "typescript";
}